Tweak console output; improve run state checks

diff --git a/adblock-lean b/adblock-lean
--- a/adblock-lean
+++ b/adblock-lean
@@ -166,6 +166,23 @@ try_mv()
 
 ### HELPER FUNCTIONS
 
+# return codes:
+# 0 - running
+# 1,2 - (reserved)
+# 3 - paused
+# 4 - stopped
+get_abl_run_state()
+{
+	local f
+	for f in "/tmp/dnsmasq.d/.blocklist.gz" "/tmp/dnsmasq.d/blocklist"
+	do
+		[ -f "${f}" ] && return 0
+	done
+
+	[ -f "${abl_dir}/prev_blocklist.gz" ] && return 3
+	return 4
+}
+
 clean_dnsmasq_dir()
 {
 	rm -f /tmp/dnsmasq.d/.blocklist.gz /tmp/dnsmasq.d/blocklist /tmp/dnsmasq.d/conf-script /tmp/dnsmasq.d/.extract_blocklist
@@ -183,19 +200,6 @@ cleanup_and_exit()
 	exit "${1}"
 }
 
-# return codes:
-# 0 - blocklist file present
-# 1 - blocklist file not present
-check_active_blocklist_file()
-{
-	local f
-	for f in "/tmp/dnsmasq.d/.blocklist.gz" "/tmp/dnsmasq.d/blocklist"
-	do
-		[ -f "${f}" ] && return 0
-	done
-	return 1
-}
-
 reg_failure()
 {
 	log_msg -err "${1}"
@@ -205,7 +209,7 @@ reg_failure()
 
 log_success()
 {
-	log_msg -green "${1}"
+	log_msg "${1}"
 	if [ -n "${report_success}" ]
 	then
 		success_msg="${1}"
@@ -619,13 +623,13 @@ check_dnsmasq()
 
 restart_dnsmasq()
 {
-	echo
+	[ "$action" = "start" ] && echo
 	reg_action -blue "Restarting dnsmasq." || return 1
 
 	/etc/init.d/dnsmasq restart &> /dev/null || 
 		{ reg_failure "Error: failed to restart dnsmasq."; return 1; }
 	
-	reg_action "Waiting for dnsmasq initialization." || return 1
+	reg_action -blue "Waiting for dnsmasq initialization." || return 1
 	local dnsmasq_ok=
 	for i in $(seq 1 60)
 	do
@@ -728,7 +732,7 @@ check_for_updates()
 			log_msg "The locally installed adblock-lean is the latest version."
 			update_check_result=0
 		else
-			log_msg "The locally installed adblock-lean seems to be outdated."
+			log_msg -yellow "The locally installed adblock-lean seems to be outdated."
 			log_msg "Consider running: 'service adblock-lean update' to update it to the latest version."
 			update_check_result=1
 		fi
@@ -943,7 +947,7 @@ init_command()
 # 1 - (optional) '-noexit' to return to the calling function
 gen_stats()
 {
-	reg_action -purple "Generating dnsmasq stats." || exit 1
+	reg_action -blue "Generating dnsmasq stats." || exit 1
 	kill -USR1 $(pgrep dnsmasq)
 	print_msg "dnsmasq stats available for reading using 'logread'."
 	[ "${1}" != '-noexit' ] && exit 0
@@ -1131,11 +1135,11 @@ start()
 			stop 1
 		fi
 
-		log_msg "Previous blocklist restored and dnsmasq check passed."
+		log_msg -green "Previous blocklist restored and dnsmasq check passed."
 		exit 1
 	fi
 
-	log_msg "The dnsmasq check passed with new blocklist file."
+	log_msg -green "The dnsmasq check passed with new blocklist file."
 	log_success "New blocklist installed with good line count: $(int2human ${good_line_count})."
 	rm -f "${abl_dir}/prev_blocklist.gz"
 
@@ -1182,7 +1186,8 @@ reload()
 # 0 - adblock-lean blocklist is loaded
 # 1 - error
 # 2 - adblock-lean is performing an action
-# 3 - adblock-lean blocklist is not loaded
+# 3 - adblock-lean is paused
+# 4 - adblock-lean is stopped
 status()
 {
 	init_command status || exit 1
@@ -1194,8 +1199,12 @@ status()
 			exit 2
 	esac
 
-	check_active_blocklist_file ||
-		{ log_msg "Blocklist in /tmp/dnsmasq.d/ not identified."; log_msg "adblock-lean is not active."; exit 3; }
+	get_abl_run_state
+	case ${?} in
+		0) ;;
+		3) log_msg -purple "adblock-lean is currently paused."; exit 3 ;;
+		4) log_msg -purple "adblock-lean is stopped."; exit 4;
+	esac
 	check_dnsmasq
 	dnsmasq_status=${?}
 	luci_dnsmasq_status=${dnsmasq_status}
@@ -1210,7 +1219,7 @@ status()
 		fi
 		luci_good_line_count=${good_line_count}
 		log_msg "The dnsmasq check passed and the presently installed blocklist has good line count: $(int2human ${good_line_count})."
-		log_msg "adblock-lean appears to be active."
+		log_msg -green "adblock-lean appears to be active."
 		gen_stats -noexit
 	else
 		reg_failure "The dnsmasq check failed with existing blocklist file."
@@ -1225,25 +1234,34 @@ status()
 pause()
 {
 	init_command pause || exit 1
-	check_active_blocklist_file || { log_msg -err "Error: adblock-lean doesn't appear to be active."; exit 1; }
+	get_abl_run_state
+	case ${?} in
+		0) ;;
+		3) log_msg -err "adblock-lean is already paused."; exit 1 ;;
+		4) log_msg -err "adblock-lean is currently stopped."; exit 1;
+	esac
 	reg_action -purple "Pausing adblock-lean." || exit 1
 	try_export_existing_blocklist || exit 1
 	restart_dnsmasq || exit 1
-	log_msg "adblock-lean is now paused."
+	log_msg -purple "adblock-lean is now paused."
 	exit 0
 }
 
 resume()
 {
 	init_command resume || exit 1
-	check_active_blocklist_file &&
-		{ log_msg -err "Error: the blocklist file exists. adblock-lean doesn't appear to be paused."; exit 1; }
+	get_abl_run_state
+	case ${?} in
+		0) log_msg -err "adblock-lean is already running."; exit 1 ;;
+		3) ;;
+		4) log_msg -err "adblock-lean is currently stopped, not paused. Can not resume."; exit 1;
+	esac
 
 	reg_action -purple "Resuming adblock-lean." || exit 1
 	restore_saved_blocklist || 
 		{ reg_failure "Error: failed to restore saved blocklist. Stopping adblock-lean."; stop 1; }
 	restart_dnsmasq || exit 1
-	log_msg "adblock-lean is now resumed."
+	log_msg -purple "adblock-lean is now resumed."
 	exit 0
 }
 
