Introduce curl and multiple blocklist file parts

diff --git a/adblock-lean b/adblock-lean
--- a/adblock-lean
+++ b/adblock-lean
@@ -9,7 +9,7 @@
 
 # *** CONFIGURATION OPTIONS ***
 
-blocklist_url="https://big.oisd.nl/dnsmasq2"
+blocklist_urls="https://big.oisd.nl/dnsmasq2 https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/pro.txt"
 min_good_line_count=100000
 max_blocklist_file_size_KB=20000
 
@@ -30,7 +30,7 @@ EXTRA_HELP="
 
 log_msg()
 {
-	local msg=${1}
+	local msg="${1}"
 	[[ -t 1 ]] && printf "${msg}\n"
 	logger -t adblock-lean "${msg}"
 }
@@ -41,7 +41,7 @@ check_blocklist_file()
 
 	blocklist_file_size_KB=`du -bk /tmp/blocklist | awk '{print $1}'`
 
-	if [[ ${blocklist_file_size_KB} -gt ${max_blocklist_file_size_KB} ]]; then
+	if [[ "${blocklist_file_size_KB}" -gt "${max_blocklist_file_size_KB}" ]]; then
 		log_msg "New blocklist file size: ${blocklist_file_size_KB} KB too large."
 		false
 		return
@@ -61,7 +61,7 @@ check_blocklist_file()
 
 	good_line_count=`sed '\|^#|d;\|^\s*$|d' /tmp/blocklist | wc -l`
 
-	if [[ ${good_line_count} -lt ${min_good_line_count} ]]; then
+	if [[ "${good_line_count}" -lt "${min_good_line_count}" ]]; then
 		log_msg "Good line count: ${good_line_count} below 100,000."
 		false
 		return
@@ -77,7 +77,7 @@ check_dnsmasq()
 
 	pgrep -x dnsmasq &> /dev/null
 	
-	if [[ ${?} -ne 0 ]]; then
+	if [[ "${?}" -ne 0 ]]; then
 		log_msg "No instance of dnsmasq detected with new blocklist."
 		false 
 		return
@@ -85,8 +85,8 @@ check_dnsmasq()
 
 	for domain in google.com amazon.com microsoft.com
 	do
-		nslookup ${domain} | grep -A1 ^Name | grep -q '^Address: *0\.0\.0\.0$'
-		if [[ ${?} -eq 0 ]]; then
+		nslookup "${domain}" | grep -A1 ^Name | grep -q '^Address: *0\.0\.0\.0$'
+		if [[ "${?}" -eq 0 ]]; then
 			log_msg "Lookup of '${domain}' resulted in 0.0.0.0 with new blocklist"
 			false
 			return
@@ -108,26 +108,42 @@ start()
 	fi
 
 	log_msg "Downloading new blocklist file."
-	
-        for retries in 1 2 3
-        do
-                wget ${blocklist_url} -O /tmp/blocklist &> /dev/null
-                if [[ ${?} -eq 0 ]]; then
-			log_msg "Download of new blocklist file suceeded."
-			break
+
+	blocklist_id=0
+	for blocklist_url in ${blocklist_urls}
+	do
+		if command -v curl &> /dev/null
+		then
+			curl --max-filesize "${max_blocklist_file_size_KB}K" --retry 3 -o "/tmp/blocklist.${blocklist_id}" "${blocklist_url}" &> /dev/null
+		else
+			for retries in 1 2 3
+			do
+				wget "${blocklist_url}" -O "/tmp/blocklist.${blocklist_id}" &> /dev/null
+				[[ "${?}" -eq 0 ]] && break
+				sleep 5
+			done
 		fi
-	
-                sleep 5
+		if [[ -f "/tmp/blocklist.${blocklist_id}" ]]
+		then
+			log_msg "Download of new blocklist file part from: ${blocklist_url} suceeded."
+		else
+			log_msg "Download of new blocklist file part from: ${blocklist_url} failed."
+		fi
+		blocklist_id=$((blocklist_id+1))
 	done
-	
-	if [[ ! -f /tmp/blocklist ]]; then
-		log_msg "Download of new blocklist file failed."
+
+	if ! ls /tmp/blocklist.* &> /dev/null 
+	then
+		log_msg "Download of at least one blocklist file part failed."
 		return
 	fi
-
+	
+	log_msg "Removing duplicates from downloaded blocklist file part(s)."
+	awk ' { if (!seen[$0]++) print $0 > "/tmp/blocklist" } ' /tmp/blocklist.*
+	rm -f /tmp/blocklist.*
 
 	check_blocklist_file
-	if [[ ${?} -ne 0 ]]; then
+	if [[ "${?}" -ne 0 ]]; then
 		log_msg "New blocklist file check failed."
 		exit
 	else
@@ -147,7 +163,7 @@ start()
 	sleep 10
 	
 	check_dnsmasq
-	if [[ ${?} -ne 0 ]]; then
+	if [[ "${?}" -ne 0 ]]; then
 		
 		log_msg "The dnsmasq check failed with new blocklist file."
 
@@ -161,7 +177,7 @@ start()
 			/etc/init.d/dnsmasq restart &> /dev/null			
 
 			check_dnsmasq
-			if [[ ${?} -ne 0 ]]; then
+			if [[ "${?}" -ne 0 ]]; then
 				log_msg "The dnsmasq check failed with previous blocklist file. Stopping adblock-lean."
 				stop
 			else
@@ -196,7 +212,7 @@ status()
 		return
 	fi
 	check_dnsmasq
-	if [[ ${?} -ne 0 ]]; then
+	if [[ "${?}" -ne 0 ]]; then
 		log_msg "The dnsmasq check failed with existing blocklist file."
 	else
 		good_line_count=`sed '\|^#|d;\|^\s*$|d' /tmp/dnsmasq.d/blocklist | wc -l`
