Handle multiple dnsmasq instances

diff --git a/adblock-lean b/adblock-lean
--- a/adblock-lean
+++ b/adblock-lean
@@ -1,5 +1,5 @@
 #!/bin/sh /etc/rc.common
-# shellcheck disable=SC3043,SC1091,SC3001,SC2018,SC2019,SC3020,SC3003,SC2181,SC2254,SC1090,SC3045
+# shellcheck disable=SC3043,SC1091,SC3001,SC2018,SC2019,SC3020,SC3003,SC2181,SC2254,SC1090,SC3045,SC2016
 
 # adblock-lean - powerful and ultra efficient adblocking with dnsmasq on OpenWrt
 
@@ -77,6 +77,53 @@ set_colors()
 {
 	set -- $(printf '\033[0;31m \033[0;32m \033[1;34m \033[1;33m \033[0;35m \033[0m')
 	red="${1}" green="${2}" blue="${3}" yellow="${4}" purple="${5}" n_c="${6}"
+}
+
+
+
+# checks if string $1 is included in newline-separated list $2
+# result via return status
+is_included() {
+	case "$2" in
+		"$1"|"$1${_NL_}"*|*"${_NL_}$1"|*"${_NL_}$1${_NL_}"*)
+			return 0 ;;
+		*)
+			return 1
+	esac
+}
+
+# adds a string to a newline-separated list if it's not included yet
+# 1 - name of var which contains the list
+# 2 - new value
+# returns 1 if bad var name, 0 otherwise
+add2list() {
+	case "${1}" in *[!A-Za-z0-9_]*)
+		return 1
+	esac
+
+	local curr_list fs=
+	eval "curr_list=\"\${${1}}\""
+	is_included "${2}" "${curr_list}" && return 0
+	case "${curr_list}" in
+		'') fs='' ;;
+		*) fs="${_NL_}" ;;
+	esac
+	eval "${1}=\"\${${1}}${fs}${2}\""
+	:
+}
+
+# 1 - var for output
+# 2 - input lines
+cnt_lines()
+{
+	local line cnt IFS="${_NL_}"
+	for line in ${2}; do
+		case "${line}" in
+			'') ;;
+			*) cnt=$((cnt+1))
+		esac
+	done
+	eval "${1}=${cnt}"
 }
 
 get_file_size_human()
@@ -249,17 +296,29 @@ pick_opt()
 
 # (optional) -d to print with allowed value types (otherwise print without)
 # (optional) -p to print with values from preset
+# (optional) -i to print with DNSMASQ_INSTANCE
 print_def_config()
 {
 	# follow each default option with '@' and a pre-defined type: string, integer (implies unsigned integer)
 	# or custom optional values, examples: opt1, opt1|opt2, ''|opt1|opt2
+
+	# process args
+	local preset='' print_types='' preset='' instance=''
+	while getopts ":i:p:d" opt; do
+		case $opt in
+			d) print_types=1 ;;
+			p) preset=$OPTARG ;;
+			i) instance=$OPTARG ;;
+			*) ;;
+		esac
+	done
 
 	mk_preset_arrays
 	: "${preset:=small}"
 	case "${preset}" in mini|small|medium|large) ;; *) reg_failure "print_def_config: \$preset var has invalid value."; exit 1; esac
 	gen_preset "${preset}" -n
 
-	cat <<-EOT | if [ "${1}" = '-d' ]; then cat; else sed 's/[ \t]*@.*//'; fi
+	cat <<-EOT | if [ -n "${print_types}" ]; then cat; else sed 's/[ \t]*@.*//'; fi
 
 	# adblock-lean configuration options
 	# config_format=v5
@@ -340,6 +399,10 @@ print_def_config()
 
 	# Crontab schedule expression for periodic list updates
 	cron_schedule="${cron_schedule:-"0 5 * * *"}" @ string
+
+	# dnsmasq instance id
+	# normally this should be set automatically by the 'setup' command
+	DNSMASQ_INSTANCE="${instance}" @ string
 
 	EOT
 }
@@ -673,10 +736,16 @@ fix_config()
 {
 	local missing_keys="${1}"
 
+	case "${missing_keys}" in
+		*DNSMASQ_INSTANCE*)
+			pick_dnsmasq_instance || exit 1
+			select_dnsmasq_conf_dir "${DNSMASQ_INSTANCE}" ;;
+	esac
+
 	# recreate config from default while replacing values with values from the existing config
 	fixed_config="$(
 		IFS=$'\n'
-		print_def_config | while read -r line
+		print_def_config -i "${DNSMASQ_INSTANCE}" | while read -r line
 		do
 			case ${line} in
 				\#*|'') printf '%s\n' "${line}"; continue ;;
@@ -731,6 +800,77 @@ write_config()
 	return 1
 }
 
+# assigns global vars:
+# DNSMASQ_INSTANCES, DNSMASQ_INSTANCES_CNT, ${instance}_IFACES, ${instance}_CONF_DIRS, ${instance}_CONF_DIRS_CNT,
+# ${instance}_INDEX, ${instance}_RUNNING
+get_dnsmasq_instances() {
+	local instance instances instance_index l1_conf_file l1_conf_files conf_dirs conf_dirs_cnt IFS_OLD _NL_ i s f
+	_NL_='
+'
+	DNSMASQ_INSTANCES=
+	DNSMASQ_INSTANCES_CNT=0
+	. /usr/share/libubox/jshn.sh
+	json_load "$(/etc/init.d/dnsmasq info)" &&
+	json_select dnsmasq &&
+	json_select instances &&
+	json_get_keys instances || return 1
+
+	instance_index=0
+	for instance in ${instances}
+	do
+		json_is_a "${instance}" object || continue # skip if $instance is not object
+		json_select "${instance}" &&
+		json_get_var "${instance}_RUNNING" running &&
+		json_is_a command array &&
+		json_select command || return 1
+
+		add2list DNSMASQ_INSTANCES "${instance}" || return 1
+		eval "${instance}_INDEX=${instance_index}"
+		instance_index=$((instance_index+1))
+
+		# look for '-C' in values, get next value which is instance's conf file
+		i=0
+		while json_is_a $((i+1)) string
+		do
+			i=$((i+1))
+			json_get_var s ${i}
+			[ "${s}" = '-C' ] || continue
+			json_get_var l1_conf_file $((i+1)) || return 1
+			add2list l1_conf_files "${l1_conf_file}" || return 1
+		done
+		json_select ..
+		json_select ..
+
+		IFS_OLD="$IFS"
+		# get ifaces for instance
+		IFS="${_NL_}"
+		ifaces="$(
+			for f in ${l1_conf_files}
+			do
+				cat "${f}" | sed -nE '/^\s*(no-dhcp-){0,1}interface=/{s/.*=//;p;}'
+			done | sort -u | sed -z 's/\n/, /'
+		)"
+		eval "${instance}_IFACES=\"${ifaces%, }\""
+
+		# get conf-dirs for instance
+		conf_dirs="$(
+			for f in ${l1_conf_files}
+			do
+				cat "${f}" | sed -n '/^\s*conf-dir=/{s/.*=//;/[^\s]/p;}'
+			done | sort -u
+		)"		
+		eval "${instance}_CONF_DIRS=\"${conf_dirs}\""
+		IFS="$IFS_OLD"
+
+		cnt_lines conf_dirs_cnt "${conf_dirs}"
+		eval "${instance}_CONF_DIRS_CNT=\"${conf_dirs_cnt}\""
+	done
+	IFS="${IFS_OLD}"
+	json_cleanup
+	cnt_lines DNSMASQ_INSTANCES_CNT "${DNSMASQ_INSTANCES}"
+	:
+}
+
 # return codes:
 # 0 - running
 # 1,2 - (reserved)
@@ -739,7 +879,7 @@ write_config()
 get_abl_run_state()
 {
 	local f
-	for f in "${dnsmasq_tmp_d}/.blocklist.gz" "${dnsmasq_tmp_d}/blocklist"
+	for f in "${DNSMASQ_CONF_D}/.blocklist.gz" "${DNSMASQ_CONF_D}/blocklist"
 	do
 		[ -f "${f}" ] && return 0
 	done
@@ -750,7 +890,8 @@ get_abl_run_state()
 
 clean_dnsmasq_dir()
 {
-	rm -f "${dnsmasq_tmp_d}"/.blocklist.gz "${dnsmasq_tmp_d}"/blocklist "${dnsmasq_tmp_d}"/conf-script "${dnsmasq_tmp_d}"/.extract_blocklist
+	rm -f "${DNSMASQ_CONF_D}"/.blocklist.gz "${DNSMASQ_CONF_D}"/blocklist \
+		"${DNSMASQ_CONF_D}"/conf-script "${DNSMASQ_CONF_D}"/.extract_blocklist
 }
 
 # exit with code ${1}
@@ -805,23 +946,26 @@ try_export_existing_blocklist()
 # return codes:
 # 0 - addnmount entry exists
 # 1 - addnmount entry doesn't exist
-# 2 - uci command not found
+# 2 - error
 check_addnmount()
 {
 	hash uci 1>/dev/null || { reg_failure "uci command was not found."; return 2; }
-	local i=0
-	while uci -q get dhcp.@dnsmasq[${i}] >/dev/null && [ ${i} -lt 128 ]
-	do
-		uci -q get dhcp.@dnsmasq[${i}].addnmount
-		i=$((i+1))
-	done | grep -qE "('|^|[ \t])/bin(/\*|/busybox)*([ \t]|'|$)" && return 0
+	local instance_index
+	eval "instance_index=\"\${${DNSMASQ_INSTANCE}_INDEX}\""
+	case "${instance_index}" in
+		''|*[!0-9]*)
+			reg_failure "Invalid index '${instance_index}' registered for dnsmasq instance '${DNSMASQ_INSTANCE}'."
+			return 2
+	esac
+
+	uci -q get dhcp.@dnsmasq["${instance_index}"].addnmount | grep -qE "('|^|[ \t])/bin(/\*|/busybox)*([ \t]|'|$)" && return 0
 	return 1
 }
 
 # return codes:
 # 0 - addnmount entry exists
 # 1 - addnmount entry doesn't exist
-# 2 - uci command not found
+# 2 - error
 check_blocklist_compression_support()
 {
 	if ! dnsmasq --help | grep -qe "--conf-script"
@@ -833,7 +977,7 @@ check_blocklist_compression_support()
 	fi
 
 	check_addnmount && return 0
-	[ ${?} = 2 ] && return 2
+	[ ${?} = 2 ] && { reg_failure "Failed to check addnmount entry for dnsmasq instance '${DNSMASQ_INSTANCE}'"; return 2; }
 	log_msg -warn "" "No appropriate 'addnmount' entry in /etc/config/dhcp was identified." \
 		"Final blocklist compression will be disabled."
 	log_msg "addnmount entry is required to give dnsmasq access to busybox gunzip in order to extract compressed blocklist." \
@@ -1374,13 +1518,29 @@ generate_and_process_blocklist_file()
 
 # return codes:
 # 0 - dnsmasq running
-# 1 - dnsmasq not running or failed to detect dnsmasq directory
-# 2 - failed to detect dnsmasq directory
+# 1 - dnsmasq instance is not running or other error
 check_dnsmasq_instance()
 {
-	! pgrep -x /usr/sbin/dnsmasq &>/dev/null && return 1
-	[ ! -d "${dnsmasq_tmp_d}" ] &&
-		{ reg_failure "Directory '${dnsmasq_tmp_d}' does not exist. Failed to detect dnsmasq directory or dnsmasq is not running."; return 2; }
+	local instance_running
+	[ -n "${DNSMASQ_INSTANCE}" ] ||
+	{
+		reg_failure "dnsmasq instance is not set."
+		return 1
+	}
+
+	get_dnsmasq_instances &&
+	eval "instance_running=\"\${${DNSMASQ_INSTANCE}_RUNNING}\"" &&
+	[ "${instance_running}" = 1 ] ||
+	{
+		reg_failure "dnsmasq instance '${DNSMASQ_INSTANCE} is misconfigured or not running."
+		return 1
+	}
+
+	[ -d "${DNSMASQ_CONF_D}" ] ||
+	{
+		reg_failure "Directory '${DNSMASQ_CONF_D}' does not exist. dnsmasq instance '${DNSMASQ_INSTANCE}' is misconfigured or not running."
+		return 1
+	}
 	:
 }
 
@@ -1449,7 +1609,7 @@ export_existing_blocklist()
 		reg_action -blue "Creating ${1} backup of existing blocklist." || return 1
 	}
 
-	local src src_d="${dnsmasq_tmp_d}" dest="${ABL_DIR}/prev_blocklist"
+	local src src_d="${DNSMASQ_CONF_D}" dest="${ABL_DIR}/prev_blocklist"
 	if [ -f "${src_d}/.blocklist.gz" ]
 	then
 		case ${use_compression} in
@@ -1518,8 +1678,8 @@ restore_saved_blocklist()
 
 import_blocklist_file()
 {
-	local src src_compressed='' src_file="${ABL_DIR}/blocklist" dest_file="${dnsmasq_tmp_d}/blocklist"
-	[ -n "${final_compress}" ] && dest_file="${dnsmasq_tmp_d}/.blocklist.gz"
+	local src src_compressed='' src_file="${ABL_DIR}/blocklist" dest_file="${DNSMASQ_CONF_D}/blocklist"
+	[ -n "${final_compress}" ] && dest_file="${DNSMASQ_CONF_D}/.blocklist.gz"
 	for src in "${src_file}" "${src_file}.gz"
 	do
 		case "${src}" in *.gz) src_compressed=1; esac
@@ -1543,8 +1703,8 @@ import_blocklist_file()
 
 	if [ -n "${final_compress}" ]
 	then
-		printf "conf-script=\"busybox sh ${dnsmasq_tmp_d}/.extract_blocklist\"\n" > "${dnsmasq_tmp_d}"/conf-script &&
-		printf "busybox gunzip -c ${dnsmasq_tmp_d}/.blocklist.gz\nexit 0\n" > "${dnsmasq_tmp_d}"/.extract_blocklist ||
+		printf "conf-script=\"busybox sh ${DNSMASQ_CONF_D}/.extract_blocklist\"\n" > "${DNSMASQ_CONF_D}"/conf-script &&
+		printf "busybox gunzip -c ${DNSMASQ_CONF_D}/.blocklist.gz\nexit 0\n" > "${DNSMASQ_CONF_D}"/.extract_blocklist ||
 			{ reg_failure "Failed to create conf-script for dnsmasq."; return 1; }
 	fi
 
@@ -1749,12 +1909,12 @@ get_active_entries_cnt()
 		list_prefixes="${list_prefixes}${list_prefix}|"
 	done
 
-	if [ -f "${dnsmasq_tmp_d}"/.blocklist.gz ]
+	if [ -f "${DNSMASQ_CONF_D}"/.blocklist.gz ]
 	then
-		gunzip -c "${dnsmasq_tmp_d}"/.blocklist.gz
-	elif [ -f "${dnsmasq_tmp_d}"/blocklist ]
+		gunzip -c "${DNSMASQ_CONF_D}"/.blocklist.gz
+	elif [ -f "${DNSMASQ_CONF_D}"/blocklist ]
 	then
-		cat "${dnsmasq_tmp_d}/blocklist"
+		cat "${DNSMASQ_CONF_D}/blocklist"
 	else
 		printf ''
 	fi |
@@ -1898,10 +2058,13 @@ init_command()
 		esac
 	fi
 
-	# set dnsmasq_tmp_d
+	# check DNSMASQ_CONF_D
 	case ${action} in boot|start|stop|status|pause|resume|update)
-		dnsmasq_tmp_d="$(uci get dhcp.@dnsmasq[0].confdir 2>/dev/null)"
-		: "${dnsmasq_tmp_d:=/tmp/dnsmasq.d}"
+		[ -n "${DNSMASQ_CONF_D}" ] ||
+		{
+			reg_failure "dnsmasq config directory is not set. Please run 'service adblock-lean setup'."
+			exit 1
+		}
 	esac
 
 	# register lock status at init
@@ -2170,18 +2333,6 @@ setup()
 		print_msg "" "${green}${ABL_SERVICE_PATH} is already executable.${n_c}"
 	fi
 
-	# make addnmount entry - enables blocklist compression to reduce RAM usage
-	check_addnmount
-	case ${?} in
-		0) print_msg "" "${green}Found existing dnsmasq addnmount UCI entry.${n_c}" ;;
-		2) exit 1 ;;
-		1)
-			print_msg "" "${purple}Creating dnsmasq addnmount UCI entry.${n_c}"
-			uci add_list dhcp.@dnsmasq[0].addnmount='/bin/busybox' && uci commit ||
-				setup_failed "Failed to create addnmount entry."
-	esac
-	luci_addnmount_failed=
-
 	REPLY=n
 	if [ -n "${do_dialogs}" ] && { [ -s "${ABL_CONFIG_FILE}" ]; }
 	then
@@ -2208,6 +2359,18 @@ setup()
 		/sbin/service adblock-lean enable || exit 1
 	fi
 	luci_service_enable_failed=
+
+	# make addnmount entry - enables blocklist compression to reduce RAM usage
+	check_addnmount
+	case ${?} in
+		0) print_msg "" "${green}Found existing dnsmasq addnmount UCI entry.${n_c}" ;;
+		2) exit 1 ;;
+		1)
+			print_msg "" "${purple}Creating dnsmasq addnmount UCI entry.${n_c}"
+			uci add_list dhcp.@dnsmasq[0].addnmount='/bin/busybox' && uci commit ||
+				setup_failed "Failed to create addnmount entry."
+	esac
+	luci_addnmount_failed=
 
 	detect_pkg_manager
 	case "$PKG_MANAGER" in
@@ -2248,6 +2411,87 @@ gen_stats()
 	[ "${1}" != '-noexit' ] && exit 0
 }
 
+pick_dnsmasq_instance() {
+	get_dnsmasq_instances && [ "${DNSMASQ_INSTANCES_CNT}" != 0 ] || return 1
+
+	if [ "${DNSMASQ_INSTANCES_CNT}" = 1 ]
+	then
+		DNSMASQ_INSTANCE="${DNSMASQ_INSTANCES}"
+		log_msg "" "Detected only 1 dnsmasq instance '${DNSMASQ_INSTANCE}' - skipping instance selection."
+		return 0
+	fi
+
+	# check if all instances share same conf-dirs
+	local instance conf_dirs conf_dirs_instance cnt REPLY first=1 diff=
+	for instance in ${DNSMASQ_INSTANCES}
+	do
+		eval "conf_dirs_instance=\"\${${instance}_CONF_DIRS}\""
+		case "${first}" in
+			1)
+				conf_dirs="${conf_dirs_instance}" ;;
+			'')
+				# conf-dirs are sorted, so we can directly compare
+				[ "${conf_dirs_instance}" = "${conf_dirs}" ] && continue
+				diff=1
+				break
+		esac
+	done
+
+	# if conf-dirs are shared, attach to first instance
+	if [ -z "${diff}" ]
+	then
+		DNSMASQ_INSTANCE="${DNSMASQ_INSTANCES%%"{_NL_}"*}"
+		log_msg "Detected multiple dnsmasq instances which are using the same conf-dir. Attaching to instance '${DNSMASQ_INSTANCE}'."
+		return 0
+	fi
+
+	# if conf-dirs are not shared, ask the user
+	log_msg "" "Multiple dnsmasq instances detected."
+	REPLY=a
+	if [ -n "${do_dialogs}" ]
+	then
+		log_msg "Active dnsmasq instances and assigned network interfaces:"
+		cnt=1
+		for instance in ${DNSMASQ_INSTANCES}
+		do
+			eval "ifaces=\"\${${instance}_IFACES}\""
+			log_msg "${cnt}. '${instance}': '${ifaces}'"
+			eval "local instance_${cnt}=\"${instance}\""
+			cnts="${cnts}${cnt}|"
+		done
+		print_msg "" "Please select which dnsmasq instance should have active adblocking, or 'a' to abort:"
+		pick_opt "${cnts}a" || exit 1
+	fi
+
+	[ "${REPLY}" = a ] && { log_msg "Aborted config generation."; exit 0; }
+	eval "DNSMASQ_INSTANCE=\"\${instance_${REPLY}}\""
+	log_msg "Selected dnsmasq instance '${DNSMASQ_INSTANCE}'."
+	return 0
+}
+
+# selects conf_dir for dnsmasq instance $1
+select_dnsmasq_conf_dir() {
+	local conf_dirs conf_dirs_cnt
+	eval "conf_dirs=\"\${${1}_CONF_DIRS}\""
+	eval "conf_dirs_cnt=\"\${${1}_CONF_DIRS_CNT}\""
+
+	if [ "${conf_dirs_cnt}" = 1 ]
+	then
+		DNSMASQ_CONF_D="${conf_dirs}"
+	else
+		if is_included "/tmp/dnsmasq.d" "${conf_dirs}"
+		then
+			DNSMASQ_CONF_D=/tmp/dnsmasq.d
+		elif is_included "/tmp/dnsmasq.cfg01411c.d" "${conf_dirs}"
+		then
+			DNSMASQ_CONF_D=/tmp/dnsmasq.cfg01411c.d
+		else
+			# fall back to first conf-dir
+			DNSMASQ_CONF_D="${conf_dirs%%"${_NL_}"*}"
+		fi
+	fi
+}
+
 # generates config
 gen_config()
 {
@@ -2286,6 +2530,10 @@ gen_config()
 
 	[ -z "${preset}" ] && { reg_failure "No config preset was selected."; return 1; }
 
+	pick_dnsmasq_instance || setup_failed "Failed to detect dnsmasq instances or no dnsmasq instances are running."
+
+	select_dnsmasq_conf_dir "${DNSMASQ_INSTANCE}" 
+
 	# create cron job
 	cron_schedule=
 	local def_schedule="0 5 * * *" def_schedule_desc="daily at 5am (5 o'clock at night)"
@@ -2319,7 +2567,7 @@ gen_config()
 		pick_opt "y|n" || return 1
 		[ "${REPLY}" = n ] && return 1
 	fi
-	write_config "$(print_def_config -p "${preset}")" || return 1
+	write_config "$(print_def_config -p "${preset}" -i "${DNSMASQ_INSTANCE}")" || return 1
 
 	check_blocklist_compression_support
 	:
@@ -2476,7 +2724,7 @@ stop()
 	msg="${msg% }"
 
 	init_command stop || exit 1
-	log_msg "Removing any adblock-lean blocklist files in ${dnsmasq_tmp_d}." || exit 1
+	log_msg "Removing any adblock-lean blocklist files in ${DNSMASQ_CONF_D}." || exit 1
 	clean_dnsmasq_dir
 	restart_dnsmasq || stop_rc=1
 	log_msg -purple "" "Stopped adblock-lean." ""
