Add rudimentary config file validation

diff --git a/adblock-lean b/adblock-lean
--- a/adblock-lean
+++ b/adblock-lean
@@ -62,6 +62,28 @@ load_config()
 		log_msg "Generate default config using 'service adblock-lean gen_config'."
 		exit
 	fi
+
+	if [[ \
+	-z "${blocklist_urls+set}" || \
+	-z "${local_allowlist_path+set}" || \
+	-z "${local_blocklist_path+set}" || \
+	-z "${min_blocklist_file_part_line_count+set}" || \
+	-z "${max_blocklist_file_part_size_KB+set}" || \
+	-z "${max_blocklist_file_size_KB+set}" || \
+	-z "${min_good_line_count+set}" || \
+	-z "${compress_blocklist+set}" || \
+	-z "${rogue_element_action+set}" || \
+	-z "${download_failed_action+set}" || \
+	-z "${report_failure+set}" || \
+	-z "${report_success+set}" || \
+	-z "${boot_start_delay_s+set}" ]]
+	then
+		log_msg "ERROR: config file entry missing."
+		log_msg "Generate new default config using 'service adblock-lean gen_config'."
+		log_msg "A new default config will be saved to: ${PREFIX}/config.new"
+		log_msg "Check differences and/or overwrite old config with the newly generated config."
+		exit
+	fi
 }
 
 gen_config()
@@ -126,6 +148,29 @@ gen_config()
 		log_msg "Saving new config file as: '${PREFIX}/config'."
 		mv "${PREFIX}/config.tmp" "${PREFIX}/config"
 	fi
+
+	check_addnmount_str
+}
+
+check_addnmount_str()
+{
+	addnmount_str=$(uci get dhcp.@dnsmasq[0].addnmount 2> /dev/null)
+
+	case "${addnmount_str}" in
+
+		/bin|/bin/busybox)
+			return 0
+			;;
+		*)
+			log_msg "Unable to use compressed blocklist."
+			log_msg "Either edit /etc/config/dhcp as described below or disable blocklist compression in config."
+			log_msg "No appropriate 'addnmount' entry in /etc/config/dhcp was identified."
+			log_msg "This is leveraged to give dnsmasq access to busybox gunzip to extract compressed blocklist."
+			log_msg "Please add: \"list addnmount '/bin/busybox'\" to /etc/config/dhcp at the end of the dnsmasq section."
+			log_msg "Or simply run this command: uci add_list dhcp.@dnsmasq[0].addnmount='/bin/busybox' && uci commit"
+			return 1
+			;;
+	esac
 }
 
 generate_preprocessed_blocklist_file_parts()
@@ -382,27 +427,12 @@ inject_blocklist_file()
 
 	if [[ "${compress_blocklist}" == 1 ]]
 	then
-		addnmount_str=$(uci get dhcp.@dnsmasq[0].addnmount 2> /dev/null)
-		case "${addnmount_str}" in
-
-			/bin|/bin/busybox) 
-				clean_dnsmasq_dir
-				printf "conf-script=\"sh /tmp/dnsmasq.d/.adblock-lean_extract\"\n" > /tmp/dnsmasq.d/adblock-lean_conf
-				printf "busybox gunzip -c /tmp/dnsmasq.d/.blocklist.gz\nexit 0\n" > /tmp/dnsmasq.d/.adblock-lean_extract
-				gzip -f /tmp/blocklist 
-				mv /tmp/blocklist.gz /tmp/dnsmasq.d/.blocklist.gz
-				injected_blocklist_file_size_KB=$(du -bk /tmp/dnsmasq.d/.blocklist.gz | awk '{print $1}')
-				return 0
-				;;
-			*) 
-				log_msg "No appropriate 'addnmount' entry in /etc/config/dhcp was identified."
-				log_msg "This is leveraged to give dnsmasq access to busybox gunzip to extract compressed blocklist."
-				log_msg "Please add: \"list addnmount '/bin/busybox'\" to /etc/config/dhcp at the end of the dnsmasq section."
-				log_msg "Or simply run this command: uci add_list dhcp.@dnsmasq[0].addnmount='/bin/busybox' && uci commit"
-				log_msg "Unable to use compressed blocklist."
-				return 1
-				;;
-		esac
+		clean_dnsmasq_dir
+		printf "conf-script=\"sh /tmp/dnsmasq.d/.adblock-lean_extract\"\n" > /tmp/dnsmasq.d/adblock-lean_conf
+		printf "busybox gunzip -c /tmp/dnsmasq.d/.blocklist.gz\nexit 0\n" > /tmp/dnsmasq.d/.adblock-lean_extract
+		gzip -f /tmp/blocklist
+		mv /tmp/blocklist.gz /tmp/dnsmasq.d/.blocklist.gz
+		injected_blocklist_file_size_KB=$(du -bk /tmp/dnsmasq.d/.blocklist.gz | awk '{print $1}')
 	else
 			clean_dnsmasq_dir
 			mv /tmp/blocklist /tmp/dnsmasq.d/blocklist
@@ -422,6 +452,11 @@ start()
 {
 
 	log_msg "Started adblock-lean."
+
+	if [[ "${compress_blocklist}" == 1 ]]
+	then
+		check_addnmount_str || exit
+	fi
 
 	extract_existing_blocklist
 
