Code cleanup, restart dnsmasq reliably

diff --git a/adblock-lean b/adblock-lean
--- a/adblock-lean
+++ b/adblock-lean
@@ -240,8 +240,8 @@ print_def_config()
 	local_allowlist_path="${PREFIX}/allowlist"
 	local_blocklist_path="${PREFIX}/blocklist"
 
-	# Whether to perform deduplication of entries (increases processing time)
-	deduplication="0"
+	# Whether to perform sorting and deduplication of entries (usually doesn't cause much slowdown, uses a bit more memory) - enable (1) or disable (0)
+	deduplication="1"
 
 	# Mininum number of lines of any individual downloaded part
 	min_blocklist_part_line_count="1"
@@ -365,7 +365,7 @@ parse_config()
 	}
 
 	local def_config='' conf_format_old='' curr_config='' missing_entries='' unexp_keys='' unexp_entries='' legacy_entries='' \
-		test_keys entry key val tab="$(printf '\t')"
+		test_keys entry key val tab="$(printf '\t')" sed_conf_san_exp='/^[ \t]*#.*$/d; s/^[ \t]*//; s/[ \t]*$//; /^$/d'
 
 	unset curr_config_format def_config_format luci_curr_config_format luci_def_config_format luci_unexp_keys luci_unexp_entries luci_missing_keys luci_missing_entries \
 		luci_legacy_entries luci_bad_conf_format luci_conf_fixes
@@ -675,7 +675,7 @@ check_blocklist_compression_support()
 
 cleanup_dl_status_files()
 {
-	rm -f "${abl_dir}/rogue_element" "${abl_dir}/dnsmasq_err" "${abl_dir}/uclient-fetch_err"
+	rm -f "${abl_dir}/rogue_element" "${abl_dir}/uclient-fetch_err"
 }
 
 # 1 - list id
@@ -724,7 +724,7 @@ process_list_part()
 	# Convert to lowercase
 	case "${list_type}" in allowlist|blocklist) tr 'A-Z' 'a-z' ;; *) cat; esac |
 	# Remove comment lines and trailing comments, remove whitespaces
-	sed "${sed_san_expr}" |
+	sed 's/#.*$//; s/^[ \t]*//; s/[ \t]*$//; /^$/d' |
 	tee >(wc -w > "${abl_dir}/list_part_line_count") |
 
 	if [ "${list_type}" = blocklist ] && [ "${use_allowlist}" = 1 ]
@@ -858,11 +858,11 @@ gen_list_parts()
 
 		for list_url in ${list_urls}
 		do
-			reg_action "Downloading, checking and sanitizing ${list_type} part from: ${list_url}." || return 1
 			list_id=$((list_id+1))
 			retry=0
 			while :
 			do
+				reg_action "Downloading, checking and sanitizing ${list_type} part from: ${list_url}." || return 1
 				retry=$((retry + 1))
 				list_part_line_count=0
 				process_list_part "${list_id}" "${list_type}" "downloaded" "${list_url}"
@@ -887,7 +887,7 @@ gen_list_parts()
 
 				if [ "${retry}" -ge "${max_download_retries}" ]
 				then
-					reg_failure "Three download attempts failed."
+					reg_failure "Three download attempts failed for URL ${list_url}."
 					handle_process_failure || return 1
 					continue 2
 				fi
@@ -928,14 +928,13 @@ generate_and_process_blocklist_file()
 	# 1 - blocklist|allowlist
 	convert_entries()
 	{
-		local entry_type extra_len len_lim=1024 allow_char=''
+		local entry_type len_lim=1024 allow_char=''
 		case "$1" in
 			blocklist) entry_type=local ;;
 			allowlist) entry_type=server allow_char="#" ;;
 		esac
-		extra_len=$((${#entry_type}+${#allow_char}+2))
 
-		len_lim=$((len_lim-extra_len))
+		len_lim=$((len_lim-${#entry_type}-${#allow_char}-2))
 		# shellcheck disable=SC2016
 		$awk_cmd -v ORS="" -v m=${len_lim} -v a="${allow_char}" -v t=${entry_type} '
 			BEGIN {al=0; r=0; s=""}
@@ -983,66 +982,74 @@ generate_and_process_blocklist_file()
 
 	[ -n "${final_compress}" ] && out_f="${out_f}.gz"
 
-	for list_type in blocklist blocklist_ipv4
-	do
-		case ${list_type} in
-			blocklist)
-				# print list parts
-				print_list_parts ${list_type} |
-				# optional deduplication
-				dedup |
-				# count entries
-				tee >(wc -wc > "${abl_dir}/${list_type}_stats") |
-				# pack entries in 1024 characters long lines
-				convert_entries ${list_type} |
+	rm -f "${abl_dir}/dnsmasq_err"
 
-				if [ "${use_allowlist}" = 1 ]
-				then
-					cat
-					cat "${abl_dir}/allowlist" |
-					# optional deduplication
-					dedup |
-					tee >(wc -wc > "${abl_dir}/allowlist_stats") |
-					# pack entries in 1024 characters long lines
-					convert_entries allowlist
-					rm -f "${abl_dir}/allowlist"
-				else
-					cat
-				fi ;;
-			blocklist_ipv4)
-				[ ! "${use_blocklist_ipv4}" ] && continue
-				# allowlist deduplication
-				print_list_parts blocklist_ipv4 |
-				# optional deduplication
-				dedup |
-				tee >(wc -wc > "${abl_dir}/blocklist_ipv4_stats") |
-				# add prefix
-				sed 's/^/bogus-nxdomain=/' ;;
-		esac
-	done |
+	{
+		# print blocklist parts
+		print_list_parts blocklist |
+		# optional deduplication
+		dedup |
+		# count entries
+		tee >(wc -wc > "${abl_dir}/blocklist_stats") |
+		# pack entries in 1024 characters long lines
+		convert_entries blocklist
+
+		# print ipv4 blocklist parts
+		if [ "${use_blocklist_ipv4}" ]
+		then
+			print_list_parts blocklist_ipv4 |
+			# optional deduplication
+			dedup |
+			tee >(wc -wc > "${abl_dir}/blocklist_ipv4_stats") |
+			# add prefix
+			sed 's/^/bogus-nxdomain=/'
+		fi
+
+		# print allowlist parts
+		if [ "${use_allowlist}" = 1 ]
+		then
+			cat "${abl_dir}/allowlist" |
+			# optional deduplication
+			dedup |
+			tee >(wc -wc > "${abl_dir}/allowlist_stats") |
+			# pack entries in 1024 characters long lines
+			convert_entries allowlist
+			rm -f "${abl_dir}/allowlist"
+		fi
+	} |
 
 	# limit size and add the blocklist test entry
 	{ head -c "${max_blocklist_file_size_KB}k"; cat 1>/dev/null; printf '%s\n' "address=/adblocklean-test123.info/127.0.0.1"; } |
 
 	# check the final blocklist with dnsmasq --test
-	tee >(dnsmasq --test -C - 2> "${abl_dir}/dnsmasq_err" && rm -f "${abl_dir}/dnsmasq_err"; cat 1>/dev/null) |
+	tee >(
+		if ! dnsmasq --test -C - 2> "${abl_dir}/dnsmasq_err"
+		then
+			touch "${abl_dir}/dnsmasq_err"
+		else
+			rm -f "${abl_dir}/dnsmasq_err"
+		fi
+		cat 1>/dev/null) |
 
 	if  [ -n "${final_compress}" ]
 	then
 		gzip
 	else
 		cat
-	fi > "${out_f}" || { reg_failure "Failed to write to output file '${out_f}'."; return 1; }
+	fi > "${out_f}" || { reg_failure "Failed to write to output file '${out_f}'."; rm -f "${out_f}"; return 1; }
 
 	if [ -f "${abl_dir}/dnsmasq_err" ]
 	then
 		rm -f "${out_f}"
 		reg_failure "The dnsmasq test on the final list failed."
+		[ ! -s "${abl_dir}/dnsmasq_err" ] && echo "No specifics: probably killed because of OOM." > "${abl_dir}/dnsmasq_err"
 		log_msg "dnsmasq --test errors:"
 		log_msg "$(head -n10 "${abl_dir}/dnsmasq_err" | sed '/^$/d')"
 		rm -f "${abl_dir}/dnsmasq_err"
 		return 2
 	fi
+
+	rm -f "${abl_dir}/dnsmasq_err"
 
 	local blocklist_entries_cnt blocklist_size_B blocklist_ipv4_entries_cnt blocklist_ipv4_size_B allowlist_entries_cnt allowlist_size_B final_list_size_B
 
@@ -1078,11 +1085,12 @@ generate_and_process_blocklist_file()
 # return codes:
 # 0 - dnsmasq running
 # 1 - dnsmasq not running or failed to detect dnsmasq directory
+# 2 - failed to detect dnsmasq directory
 check_dnsmasq_instance()
 {
-	! pgrep -x /usr/sbin/dnsmasq &>/dev/null && { reg_failure "No running instance of dnsmasq detected."; return 1; }
+	! pgrep -x /usr/sbin/dnsmasq &>/dev/null && return 1
 	[ ! -d "${dnsmasq_tmp_d}" ] &&
-		{ reg_failure "Directory '${dnsmasq_tmp_d}' does not exist. Failed to detect dnsmasq directory or dnsmasq is not running."; return 1; }
+		{ reg_failure "Directory '${dnsmasq_tmp_d}' does not exist. Failed to detect dnsmasq directory or dnsmasq is not running."; return 2; }
 	:
 }
 
@@ -1097,7 +1105,7 @@ check_active_blocklist()
 	echo
 	reg_action -blue "Checking active blocklist." || return 1
 
-	check_dnsmasq_instance || return 1
+	check_dnsmasq_instance || { [ ${?} = 1 ] && reg_failure "No running instance of dnsmasq detected."; return 1; }
 
 	nslookup "adblocklean-test123.info" 127.0.0.1 1>/dev/null 2>/dev/null ||
 			{ reg_failure "Lookup of the blocklist test domain failed with new blocklist."; return 4; }
@@ -1119,8 +1127,7 @@ restart_dnsmasq()
 	[ "$action" = "start" ] && echo
 	reg_action -blue "Restarting dnsmasq." || return 1
 
-	/etc/init.d/dnsmasq restart &> /dev/null || 
-		{ reg_failure "Failed to restart dnsmasq."; return 1; }
+	/etc/init.d/dnsmasq restart &> /dev/null || { reg_failure "Failed to restart dnsmasq."; stop 1; }
 	
 	reg_action "Waiting for dnsmasq initialization." || return 1
 	local dnsmasq_ok=
@@ -1130,7 +1137,7 @@ restart_dnsmasq()
 		sleep 1;
 	done
 
-	[ -z "$dnsmasq_ok" ] && { reg_failure "dnsmasq initialization failed."; return 1; }
+	[ -z "$dnsmasq_ok" ] && { reg_failure "dnsmasq initialization failed."; stop 1; }
 
 	log_msg -green "Restart of dnsmasq completed."
 	:
@@ -1501,7 +1508,7 @@ init_command()
 			try_mkdir -p "${abl_dir}" || exit 1
 			load_config || { reg_failure "Failed to load config."; exit 1; } ;;
 		start|boot|pause|resume|update)
-			check_dnsmasq_instance || exit 1
+			check_dnsmasq_instance || { [ ${?} = 1 ] && reg_failure "No running instance of dnsmasq detected."; exit 1; }
 			try_mkdir -p "${abl_dir}" || exit 1
 			load_config || { reg_failure "Failed to load config."; exit 1; }
 			if [ -n "${custom_script}" ]
@@ -1653,7 +1660,6 @@ start()
 
 		if ! restart_dnsmasq
 		then
-			log_msg "Stopping adblock-lean."
 			stop 1
 		fi
 
@@ -1667,7 +1673,7 @@ start()
 		exit 1
 	fi
 
-	log_msg -green "Active blocklist check passed with new blocklist file."
+	log_msg -green "Active blocklist check passed with the new blocklist file."
 	log_success "New blocklist installed with entries count: $(int2human "${final_entries_cnt}")."
 	rm -f "${abl_dir}/prev_blocklist.gz"
 
@@ -1693,7 +1699,7 @@ stop()
 	init_command stop || exit 1
 	reg_action "Removing any adblock-lean blocklist files in ${dnsmasq_tmp_d}/ and restarting dnsmasq." || exit 1
 	clean_dnsmasq_dir
-	/etc/init.d/dnsmasq restart &> /dev/null
+	restart_dnsmasq || stop_rc=1
 	log_msg -purple "Stopped adblock-lean."
 	[ -n "$noexit" ] && return "${stop_rc}"
 	exit "${stop_rc}"
@@ -1709,6 +1715,41 @@ restart()
 reload()
 {
 	restart
+}
+
+get_active_entries_cnt()
+{
+	local cnt entry_type allow_opt='' list_prefix list_prefixes=
+
+	# 'blocklist_ipv4' prefix doesn't need to be added for counting
+	for entry_type in blocklist allowlist
+	do
+		eval "[ ! \"\${${entry_type}_urls}\" ] && [ ! -s \"\${local_${entry_type}_path}\" ]" && continue
+		case ${entry_type} in
+			blocklist) list_prefix=local ;;
+			allowlist) list_prefix=server allow_opt="|#"
+		esac
+		list_prefixes="${list_prefixes}${list_prefix}|"
+	done
+
+	if [ -f "${dnsmasq_tmp_d}"/.blocklist.gz ]
+	then
+		gunzip -c "${dnsmasq_tmp_d}"/.blocklist.gz
+	elif [ -f "${dnsmasq_tmp_d}"/blocklist ]
+	then
+		cat "${dnsmasq_tmp_d}/blocklist"
+	else
+		printf ''
+	fi |
+	sed -E "s~^(${list_prefixes%|})\=/~~;" | tr "[/${allow_opt}]" '\n' |
+	wc -w > "/tmp/abl_entries_cnt"
+
+	read -r cnt _ < "/tmp/abl_entries_cnt" || cnt=0
+	case ${cnt} in
+		[0-2]|'') printf 0; return 1 ;;
+		*) printf %s "$((cnt-3))" # to account for the blocklist test entry
+	esac
+	:
 }
 
 # return codes:
@@ -1727,7 +1768,6 @@ status()
 			report_pid_action
 			exit 2
 	esac
-
 	get_abl_run_state
 	case ${?} in
 		0) ;;
@@ -1736,40 +1776,13 @@ status()
 	esac
 	check_active_blocklist; local dnsmasq_status=${?}
 	luci_dnsmasq_status=${dnsmasq_status}
-	local list_prefix list_prefixes=
-	# 'blocklist_ipv4' prefix doesn't need to be added for counting
-	for entry_type in blocklist allowlist
-	do
-		eval "[ ! \"\${${entry_type}_urls}\" ]" && continue
-		case ${entry_type} in
-			blocklist) list_prefix=local ;;
-			allowlist) list_prefix=server
-		esac
-		list_prefixes="${list_prefixes}${list_prefix}|"
-	done
 
 	local active_entries_cnt=0
+
 	if [ ${dnsmasq_status} = 0 ]
 	then
-		active_entries_cnt="$(
-			if [ -f "${dnsmasq_tmp_d}"/.blocklist.gz ]
-			then
-				gunzip -c "${dnsmasq_tmp_d}"/.blocklist.gz
-			elif [ -f "${dnsmasq_tmp_d}"/blocklist ]
-			then
-				cat "${dnsmasq_tmp_d}/blocklist"
-			else
-				printf ''
-			fi |
-			sed -E "s~^(${list_prefixes%|})=/~~;s~/~\n~g;" |
-			wc -w
-		)"
-		case ${active_entries_cnt} in
-			[0-2]|'')
-				active_entries_cnt=0
-				reg_failure "Entries count in the final blocklist is '${active_entries}' which can not happen with normal operation." ;;
-			*) active_entries_cnt=$((active_entries_cnt-3)) # to account for the blocklist test entry
-		esac
+		active_entries_cnt="$(get_active_entries_cnt)" || reg_failure "No entries found in the blocklist file."
+
 		luci_min_good_line_count=${active_entries_cnt}
 		log_msg "The dnsmasq check passed and the presently installed blocklist has entries count: $(int2human ${active_entries_cnt})."
 		log_msg -green "adblock-lean is active."
@@ -1812,8 +1825,7 @@ resume()
 	esac
 
 	reg_action -purple "Resuming adblock-lean." || exit 1
-	restore_saved_blocklist || 
-		{ reg_failure "Failed to restore saved blocklist. Stopping adblock-lean."; stop 1; }
+	restore_saved_blocklist || { reg_failure "Failed to restore saved blocklist."; stop 1; }
 	restart_dnsmasq || exit 1
 	log_msg -purple "adblock-lean is now resumed."
 	exit 0
@@ -1874,7 +1886,5 @@ update()
 }
 
 set_colors
-sed_san_expr='s/#.*$//; s/^[ \t]*//; s/[ \t]*$//; /^$/d'
-sed_conf_san_exp='/^[ \t]*#.*$/d; s/^[ \t]*//; s/[ \t]*$//; /^$/d'
 
 :
