Implement cron task creation/removal; improve preset logic

diff --git a/adblock-lean b/adblock-lean
--- a/adblock-lean
+++ b/adblock-lean
@@ -40,25 +40,27 @@ abl_dir=/var/run/adblock-lean
 abl_pid_dir=/tmp/adblock-lean
 update_log_file=/var/log/abl_update.log
 session_log_file=/var/log/abl_session.log
+hagezi_dl_url="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard"
+abl_cron_cmd="/etc/init.d/adblock-lean start"
 
 export PATH=/usr/sbin:/usr/bin:/sbin:/bin
 export HOME=/root
-hagezi_dl_url="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard"
 
 START=99
 STOP=4
 
-EXTRA_COMMANDS="setup status pause resume gen_stats gen_config print_log update"
-EXTRA_HELP="	
+EXTRA_COMMANDS="setup status pause resume gen_stats gen_config update_cron_job print_log update"
+EXTRA_HELP="
 adblock-lean custom commands:
-	setup		run automated setup for adblock-lean
-	status		check dnsmasq and entries count of existing blocklist
-	pause		pause adblock-lean
-	resume		resume adblock-lean
-	gen_stats	generate dnsmasq stats for system log
-	gen_config	generate default config
-	print_log	print most recent session log
-	update		update adblock-lean to the latest version"
+	setup			run automated setup for adblock-lean
+	status			check dnsmasq and entries count of existing blocklist
+	pause			pause adblock-lean
+	resume			resume adblock-lean
+	gen_stats		generate dnsmasq stats for system log
+	gen_config		generate default config
+	update_cron_job	create cron job for adblock-lean with schedule set in the config option 'cron_schedule' 
+	print_log		print most recent session log
+	update			update adblock-lean to the latest version"
 
 
 ### UTILITY FUNCTIONS
@@ -245,12 +247,14 @@ print_def_config()
 	# or custom optional values, examples: opt1, opt1|opt2, ''|opt1|opt2
 
 	local preset
+	mk_preset_arrays
 	if [ "${1}" = '-p' ]
 	then
 		preset="${2}"
 	else
-		preset=small
+		mk_def_preset || { print_msg "Falling back to preset 'small'."; preset=small; }
 	fi
+
 	case "${preset}" in mini|small|medium|large) ;; *) reg_failure "print_def_config: \$preset var has invalid value."; exit 1; esac
 	gen_preset "${preset}" -n
 
@@ -321,7 +325,61 @@ print_def_config()
 	# Start delay in seconds when service is started from system boot
 	boot_start_delay_s="120" @ integer
 
+	# Crontab schedule expression for periodic list updates
+	cron_schedule="${cron_schedule:-"0 5 * * *"}" @ string
+
 	EOT
+}
+
+# 1 - mini|small|medium|large
+# 2 - (optional) '-d' to print the description
+# 2 - (optional) '-n' to print nothing (only assign values to vars)
+gen_preset()
+{
+	local val field mem cnt i=1
+	eval "mem=\"\${${1}_mem}\" cnt=\"\${${1}_cnt}\""
+	[ "${2}" = '-d' ] && print_msg "" "${purple}${1}${n_c}: recommended for devices with ${mem} MB of memory."
+	[ "${2}" != '-n' ] && print_msg "${blue}Elements count:${n_c} ~${cnt}k"
+	for field in blocklist_urls max_file_part_size_KB max_blocklist_file_size_KB min_good_line_count
+	do
+		eval "val=\"\${${1}_${i}}\""
+		eval "${field}=\"${val}\""
+		[ "${2}" != '-n' ] && print_msg "${blue}${field}${n_c}=\"${val}\""
+		i=$((i+1))
+	done
+}
+
+mk_preset_arrays()
+{
+	# quasi-arrays for presets: 1 - url, 2 - max part size, 3 - max blocklist size, 4 - min line count,
+	# cnt - elements count/1000, mem - memory in MB
+	mini_1="${hagezi_dl_url}/pro.mini-onlydomains.txt" \
+		mini_2=4000 mini_3=4000 mini_4=40000 mini_cnt=85 mini_mem=64
+	small_1="${hagezi_dl_url}/pro-onlydomains.txt ${hagezi_dl_url}/tif.mini-onlydomains.txt" \
+		small_2=7000 small_3=10000 small_4=100000 small_cnt=250 small_mem=128
+	medium_1="${hagezi_dl_url}/pro-onlydomains.txt ${hagezi_dl_url}/tif.medium-onlydomains.txt ${hagezi_dl_url}/popupads-onlydomains.txt" \
+		medium_2=10000 medium_3=20000 medium_4=200000 medium_cnt=350 medium_mem=256
+	large_1="${hagezi_dl_url}/pro-onlydomains.txt ${hagezi_dl_url}/tif-onlydomains.txt" \
+		large_2=30000 large_3=50000 large_4=200000 large_cnt=700 large_mem=512
+}
+
+# determine recommended preset and set quasi-array variables
+mk_def_preset()
+{
+	unset preset totalmem
+	local mem cnt
+	read -r _ totalmem _ </proc/meminfo
+	case "${totalmem}" in
+		''|*[!0-9]*) reg_failure "Failed to determine system memory capacity." ;;
+		*)
+			for preset in large medium small mini
+			do
+				eval "mem=\"\${${preset}_mem}\""
+				# multiplying by 900 rather than 1024 to account for some memory not available to the kernel
+				[ "${totalmem}" -ge $((mem * 900)) ] && break
+			done
+	esac
+	:
 }
 
 # get config format from config file contents
@@ -976,8 +1034,8 @@ cleanup_dl_status_files()
 # 3 - Download Failure (retry makes sense)
 process_list_part()
 {
-	local list_id="${1}" list_type="${2}" list_origin="${3}" list_format="${4}" list_path="${5}" me="process_list_part"
-	local dest_file="${abl_dir}/${list_type}.${list_id}" compress_part='' \
+	local list_id="${1}" list_type="${2}" list_origin="${3}" list_format="${4}" list_path="${5}" me="process_list_part" \
+		dest_file="${abl_dir}/${list_type}.${list_id}" compress_part='' \
 		min_list_part_line_count='' list_part_size_B='' list_part_size_KB='' val_entry_regex
 
 	for v in 1 2 3 4 5; do
@@ -1774,6 +1832,64 @@ report_pid_action()
 	:
 }
 
+### Cron-related functions
+
+rm_cron_job()
+{
+	local curr_cron
+	log_msg -yellow "Removing cron job for adblock-lean."
+	curr_cron="$(crontab -u root -l 2>/dev/null)" || return 1
+	case "${curr_cron}" in
+		*"adblock-lean start"*) ;;
+		*) log_msg "Cron job for adblock-lean is not present."; return 0
+	esac
+
+	printf '%s\n' "${curr_cron}" | sed '/adblock-lean start/d;/^$/d' | crontab -u root - ||
+		{ reg_failure "Failed to update crontab."; return 1; }
+	:
+}
+
+# checks if the cron service is enabled and running
+# if not enabled or not running or if crontab doesn't exist, implements automatic correction
+# return codes: 0 - success, 1 - failure
+enable_cron_service()
+{
+	# returns 0 if crontab is readable and the crond process is running, 1 otherwise
+	# sets $cron_reboot if above conditions are satisfied and cron is not implemented via the busybox binary
+	check_cron_service()
+	{
+		# check if service is enabled
+		${cron_service_path} enabled || return 1
+		# check reading crontab
+		crontab -u root -l &>/dev/null || return 1
+		# check for crond in running processes
+		pidof crond 1>/dev/null || return 1
+		:
+	}
+
+	local cron_service_path="/etc/init.d/cron" enable_failed="Failed to enable and start the cron service"
+
+	hash crontab || { reg_failure "${enable_failed}: 'crontab' utility is inaccessible."; return 1; }
+	[ -f "${cron_service_path}" ] || { reg_failure "${enable_failed}: the cron service was not found at path '${cron_service_path}'."; return 1; }
+
+	check_cron_service && return 0
+	log_msg -warn "The cron service is not enabled or not running."
+
+	printf '\n%s' "${purple}Attempting to enable and start the cron service...${n_c} " > "${msgs_dest}"
+
+	# if crontab doesn't exist yet, try to create an empty crontab
+	crontab -u root -l &>/dev/null || printf '' | crontab -u root -
+
+	# try to enable and start the cron service
+	${cron_service_path} enabled 1>/dev/null || ${cron_service_path} enable && { ${cron_service_path} start; sleep 2; }
+
+	check_cron_service || { printf '%s\n' "${red}Failed.${n_c}"; reg_failure "${enable_failed}."; return 1; }
+	printf '%s\n' "${green}OK${n_c}" > "${msgs_dest}"
+	:
+}
+
+### Commands init
+
 init_command()
 {
 	action="${1}"
@@ -1792,7 +1908,7 @@ init_command()
 
 	# set requirements
 	case ${action} in
-		help|status|gen_stats|print_log|enabled|enable|disable|'') ;;
+		help|status|gen_stats|print_log|enabled|enable|disable|update_cron_job|'') ;;
 		setup|gen_config|pause) lock_req=1 ;;
 		boot|start|update|resume) cleanup_req=1 lock_req=1 ;;
 		stop)
@@ -1867,26 +1983,45 @@ init_command()
 	:
 }
 
-# 1 - mini|small|medium|large
-# 2 - (optional) '-d' to print the description
-# 2 - (optional) '-n' to print nothing (only assign values to vars)
-gen_preset()
-{
-	local val field mem cnt i=1
-	eval "mem=\"\${${1}_mem}\" cnt=\"\${${1}_cnt}\""
-	[ "${2}" = '-d' ] && print_msg "" "${purple}${1}${n_c}: recommended for devices with ${mem} MB of memory."
-	[ "${2}" != '-n' ] && print_msg "${blue}Elements count:${n_c} ~${cnt}k"
-	for field in blocklist_urls max_file_part_size_KB max_blocklist_file_size_KB min_good_line_count
-	do
-		eval "val=\"\${${1}_${i}}\""
-		eval "${field}=\"${val}\""
-		[ "${2}" != '-n' ] && print_msg "${blue}${field}${n_c}=\"${val}\""
-		i=$((i+1))
-	done
-}
-
 
 ### MAIN COMMAND FUNCTIONS
+
+update_cron_job()
+{
+	local me="update_cron_job" curr_cron cron_line
+
+	log_msg -purple "" "Updating cron job for adblock-lean."
+
+	if [ "${action}" = update_cron_job ]
+	then
+		load_config || return 1
+	fi
+
+	[ -z "${cron_schedule}" ] && { reg_failure "${me}: the \$cron_schedule variable is unset."; return 1; }
+	case "${cron_schedule}" in disable) rm_cron_job; return 0; esac
+
+	enable_cron_service || return 1
+
+	curr_cron="$(crontab -u root -l 2>/dev/null)" || { reg_failure "${me}: Failed to read crontab."; return 1; }
+
+	# check if adblock-lean cron job with same schedule exists
+	case "${curr_cron}" in
+		*"${cron_schedule}"*"${abl_cron_cmd}"*)
+			print_msg "${green}Cron job for adblock-lean with schedule '${cron_schedule}' aldready exists.${n_c}"; return 0 ;;
+		*"${abl_cron_cmd}"*)
+			# remove existing cron job with a different schedule from $curr_cron
+			curr_cron="$(printf %s "${curr_cron}" | sed "s~^.*${abl_cron_cmd}.*\$~~")" ;;
+		*) ;; # no adblock-lean cron job exists
+	esac
+
+	cron_line="${cron_schedule} RANDOM_DELAY=1 ${abl_cron_cmd} 1>/dev/null"
+
+	#### Create new cron job
+	printf '%s\n' "${curr_cron}${nl}${cron_line}" | sed '/^$/d' | crontab -u root - ||
+		{ reg_failure "Failed to update crontab."; return 1; }
+	log_msg "Creating cron job with schedule '${blue}${cron_schedule}${n_c}'."
+	:
+}
 
 setup()
 {
@@ -1904,6 +2039,9 @@ setup()
 			sort) printf coreutils-sort
 		esac
 	}
+
+	# set all luci feedback vars to failed, unset later upon success
+	luci_addnmount_failed=1 luci_service_enable_failed=1 luci_pkgs_install_failed=1 luci_cron_job_creation_failed=1
 
 	init_command setup
 	[ -z "${abl_service_path}" ] && setup_failed "\${abl_service_path} variable is unset."
@@ -1927,6 +2065,7 @@ setup()
 			print_msg "" "${purple}Creating dnsmasq addnmount UCI entry.${n_c}"
 			uci add_list dhcp.@dnsmasq[0].addnmount='/bin/busybox' && uci commit || setup_failed "Failed to create addnmount entry."
 	esac
+	luci_addnmount_failed=
 
 	# generate config
 	gen_config
@@ -1937,12 +2076,13 @@ setup()
 		print_msg "" "${purple}Enabling the adblock-lean service.${n_c}"
 		/sbin/service adblock-lean enable || setup_failed "Failed to enable the adblock-lean service."
 	else
-		print_msg "" "${green}adblock-lean service is already enabled.${n_c}"
+		print_msg "" "The ${green}adblock-lean service is already enabled.${n_c}"
 	fi
+	luci_service_enable_failed=
 
 	# determine if there are missing GNU utils
 	local pkgs2install='' missing_packages='' missing_utils='' missing_utils_print='' util package \
-		util_size utils_size_KB=0 awk_size=460 sort_size=120 sed_size=150 \
+		util_size_B utils_size_B=0 awk_size_B=1048576 sort_size_B=122880 sed_size_B=153600 \
 		installed_utils="$(opkg list_installed | grep -E '^[ \t]*(sed|gawk|coreutils-sort)([ \t]|$)')"
 
 	echo
@@ -1980,8 +2120,8 @@ setup()
 			REPLY=n
 			if [ -n "${do_dialogs}" ]
 			then
-				eval "util_size=\"\${${util}_size}\""
-				print_msg "Would you like to install ${blue}GNU ${util}${n_c} automatically? Installed size: ${yellow}${util_size} KiB${n_c}."
+				eval "util_size_B=\"\${${util}_size_B}\""
+				print_msg "Would you like to install ${blue}GNU ${util}${n_c} automatically? Installed size: ${yellow}$(bytes2human "${util_size_B}")${n_c}."
 				pick_opt "y|n" || exit 1
 			elif [ -n "${luci_install_packages}" ]
 			then
@@ -1991,7 +2131,7 @@ setup()
 			if [ "${REPLY}" = y ]
 			then
 				pkgs2install="${pkgs2install}$(get_package_name "${util}") "
-				utils_size_KB=$((utils_size_KB+util_size))
+				utils_size_B=$((utils_size_B+util_size_B))
 			fi
 		done
 	fi
@@ -1999,7 +2139,6 @@ setup()
 	# install GNU utils
 	if [ -n "${pkgs2install}" ]
 	then
-		local utils_size_B="$((utils_size_KB*1024))"
 		REPLY=n
 		if [ -n "${do_dialogs}" ]
 		then
@@ -2011,12 +2150,13 @@ setup()
 		then
 			REPLY=y
 		fi
+
 		if [ "${REPLY}" = y ]
 		then
 			if [ -z "${free_space_B}" ] || [ -z "${utils_size_B}" ] || [ ${free_space_B} -gt ${utils_size_B} ]
 			then
 				echo
-				opkg update && opkg install ${pkgs2install% } ||
+				opkg update && opkg install ${pkgs2install% } && luci_pkgs_install_failed='' ||
 					reg_failure "Failed to automatically install packages. You can install them manually later."
 			else
 				reg_failure "Not enough free space at mount point '${mount_point}'."
@@ -2024,6 +2164,8 @@ setup()
 					"opkg update; opkg install ${pkgs2install% }"
 			fi
 		fi
+	else
+		luci_pkgs_install_failed=
 	fi
 
 	if [ -n "${do_dialogs}" ]
@@ -2059,39 +2201,15 @@ gen_config()
 {
 	init_command gen_config || exit 1
 
-	# quasi-arrays for default presets: 1 - url, 2 - max part size, 3 - max blocklist size, 4 - min line count,
-	# cnt - elements count/1000, mem - memory in MB
-	local mini_1="${hagezi_dl_url}/pro.mini-onlydomains.txt" \
-		mini_2=4000 mini_3=4000 mini_4=40000 mini_cnt=85 mini_mem=64
-	local small_1="${hagezi_dl_url}/pro-onlydomains.txt ${hagezi_dl_url}/tif.mini-onlydomains.txt" \
-		small_2=7000 small_3=10000 small_4=100000 small_cnt=250 small_mem=128
-	local medium_1="${hagezi_dl_url}/pro-onlydomains.txt ${hagezi_dl_url}/tif.medium-onlydomains.txt ${hagezi_dl_url}/popupads-onlydomains.txt" \
-		medium_2=10000 medium_3=20000 medium_4=200000 medium_cnt=350 medium_mem=256
-	local large_1="${hagezi_dl_url}/pro-onlydomains.txt ${hagezi_dl_url}/tif-onlydomains.txt" \
-		large_2=30000 large_3=50000 large_4=200000 large_cnt=700 large_mem=512
-
-	local preset='' mem totalmem cnt
-
-	# determine recommended preset
-	read -r _ totalmem _ </proc/meminfo
-	case "${totalmem}" in
-		''|*[!0-9]*)
-			reg_failure "Failed to determine system memory capacity."
-			print_msg "Skipping automatic preset recommendation." ;;
-		*)
-			for preset in large medium small mini
-			do
-				eval "mem=\"\${${preset}_mem}\""
-				# multiplying by 900 rather than 1024 to account for some memory not available to the kernel
-				[ "${totalmem}" -ge $((mem * 900)) ] && break
-			done
-	esac
+	local preset cnt
 
 	if [ -n "${do_dialogs}" ] && [ -z "${luci_preset}" ]
 	then
+		mk_preset_arrays
+		mk_def_preset || print_msg "Skipping automatic preset recommendation."
 		if [ -n "${preset}" ]
 		then
-			print_msg "" "Based on the total usable memory of this device ($(bytes2human $((totalmem*1024)) )), the recommended preset is ${purple}${preset}${n_c}:"
+			print_msg "" "Based on the total usable memory of this device ($(bytes2human $((totalmem*1024)) )), the recommended preset is '${purple}${preset}${n_c}':"
 			gen_preset "${preset}"
 			print_msg "" "[C]onfirm this preset or [p]ick another preset?"
 			pick_opt "c|p"
@@ -2116,14 +2234,43 @@ gen_config()
 
 	[ -z "${preset}" ] && { reg_failure "No config preset was selected."; exit 1; }
 
+	# create cron job
+	cron_schedule=
+	local def_schedule="0 5 * * *" def_schedule_desc="daily at 5am (5 o'clock at night)"
+
+	REPLY=n
+	if [ -n "${do_dialogs}" ]
+	then
+		print_msg "" "${purple}Cron job configuration:${n_c}" \
+			"A cron job can be created to enable automatic list updates." \
+			"The default schedule is '${blue}${def_schedule}${n_c}': ${def_schedule_desc}" \
+			"The cron job will run with an added random number of minutes." \
+			"" "Create cron job with default schedule for automatic list updates?" \
+			"If you enter 'n', you can later create a cron job with a custom schedule as described in:" \
+			"https://github.com/lynxthecat/adblock-lean/blob/master/README.md"
+		pick_opt "y|n" || exit 1
+		cron_schedule="${def_schedule}"
+	elif [ -n "${luci_update_cron_job}" ] && [ -n "${luci_cron_schedule}" ]
+	then
+		REPLY=y
+		cron_schedule="${luci_cron_schedule}"
+	elif  [ -n "${luci_update_cron_job}" ]
+	then
+		reg_failure "Can not create cron job for luci because the \${luci_cron_schedule} var is empty."
+	fi
+	[ "${REPLY}" = n ] && cron_schedule=disable
+
 	reg_action -purple "Generating new default config for adblock-lean from preset '${preset}'." || exit 1
 	if [ -n "${do_dialogs}" ] && [ -f "${config_file}" ]
 	then
-		print_msg "This will overwrite existing config with default one. Proceed?"
+		print_msg "This will overwrite existing config. Proceed?"
 		pick_opt "y|n" || exit 1
 		[ "${REPLY}" = n ] && exit 1
 	fi
 	write_config "$(print_def_config -p "${preset}")" || exit 1
+
+	update_cron_job && luci_cron_job_creation_failed=''
+
 	mk_new_urls_format_flag || exit 1 # @url_conversion_logic
 	check_blocklist_compression_support
 	:
@@ -2451,5 +2598,20 @@ update()
 
 set_colors
 
-[ "${1}" = setup ] && setup
+[ "${1}" = setup ] && { setup; exit 0; }
+
+case "${action}" in
+	enable)
+		log_msg -purple "Enabling adblock-lean."
+		load_config
+		update_cron_job ;;
+	disable)
+		log_msg -purple "Disabling adblock-lean."
+		load_config
+		case "${cron_schedule}" in
+			''|disable) ;;
+			*) rm_cron_job
+		esac
+esac
+
 :
