Improve handling of legacy config entries

diff --git a/adblock-lean b/adblock-lean
--- a/adblock-lean
+++ b/adblock-lean
@@ -142,15 +142,15 @@ print_msg()
 
 log_msg()
 {
-	local msg='' _arg='' err_l=info color=
+	local msg='' msg_prefix='' _arg err_l=info color=
 
 	for _arg in "$@"; do
 		case "${_arg}" in
-			"-err") err_l=err; color="${red}" ;;
-			"-warn") err_l=warn; color="${yellow}" ;;
+			"-err") err_l=err color="${red}" msg_prefix="Error: " ;;
+			"-warn") err_l=warn color="${yellow}" msg_prefix="Warning: " ;;
 			-blue|-red|-green|-purple|-yellow) eval "color=\"\${${_arg#-}}\"" ;;
 			'') ;;
-			*) msg="${msg}${_arg} "
+			*) msg="${msg}${msg_prefix}${_arg} "
 		esac
 	done
 	msg="${msg% }"
@@ -162,7 +162,7 @@ log_msg()
 try_mv()
 {
 	[ -z "${1}" ] || [ -z "${2}" ] && { reg_failure "try_mv(): bad arguments."; return 1; }
-	mv -f "${1}" "${2}" || { reg_failure "Error: failed to rename '${1}'."; return 1; }
+	mv -f "${1}" "${2}" || { reg_failure "Failed to rename '${1}'."; return 1; }
 	:
 }
 
@@ -254,7 +254,7 @@ parse_config() {
 	inval_e()
 	{
 		IFS="${default_IFS}"
-		reg_failure "Error: Invalid entry '$entry' in config."
+		reg_failure "Invalid entry '$entry' in config."
 	}
 
 	# Following 2 function are needed to minimize ugly hacks and tinkering inside eval
@@ -262,16 +262,25 @@ parse_config() {
 	parse_entry()
 	{
 		val=${entry#"${key}="}
+
+		# Following 'case' is a temporarily solution to allow easy config migration - remove a few months from now (Aug 2024)
+		case "${entry}" in
+			"compress_blocklist="?" #"*|"initial_dnsmasq_restart="?" #"*)
+				legacy_entries="${legacy_entries}${entry}"$'\n'; legacy_keys="${legacy_keys}${key} "
+				test_keys="${test_keys%%"${key}|"*}${test_keys#*"${key}|"}"
+				val=${val%% *}
+				return 0
+		esac
+
 		case "${val}" in
 			\"*\"*\") inval_e; return 1 ;; # do not allow more than 2 double-quote marks
 			\"*\"*) ;;
 			*\"*) inval_e; return 1 ;; # do not allow 1 double-quote mark
 			*"#"*) inval_e; return 1 ;; # do not allow in-line comments without double-quote marks
-			*) conv_entries="${conv_entries}${entry}"$'\n'; conv_keys="${conv_keys}${key} "
+			*) legacy_entries="${legacy_entries}${entry}"$'\n'; legacy_keys="${legacy_keys}${key} "
 		esac
 		val=${val#\"}
 		val=${val%\"*} # throw away everything after the 2nd double-quote mark
-
 		test_keys="${test_keys%%"${key}|"*}${test_keys#*"${key}|"}" # remove current key from test_keys
 	}
 
@@ -281,11 +290,11 @@ parse_config() {
 		unexp_entries="${unexp_entries}${entry}"$'\n'
 	}
 
-	local def_config bad_config='' must_convert='' curr_config test_keys entry key val
+	local def_config bad_config='' curr_config test_keys entry key val
 
 	[ -z "${1}" ] && { reg_failure "parse_config(): no file specified."; return 1; }
 
-	[ ! -f "${1}" ] && { reg_failure "Error: config file '${1}' not found."; return 1; }
+	[ ! -f "${1}" ] && { reg_failure "Config file '${1}' not found."; return 1; }
 
 	# extract entries from default config
 	def_config="$(print_def_config | sed "${sed_conf_san_exp}")"
@@ -295,7 +304,7 @@ parse_config() {
 	test_keys="dummy|$(print_def_config | sed "${sed_conf_san_exp}"'s/=.*//' | tr '\n' '|')"
 
 	# read and sanitize current config
-	curr_config="$(sed "${sed_conf_san_exp}" "${1}")" || { reg_failure "Error: failed to read the config file '${1}'."; return 1; }
+	curr_config="$(sed "${sed_conf_san_exp}" "${1}")" || { reg_failure "Failed to read the config file '${1}'."; return 1; }
 
 	local IFS=$'\n'
 	for entry in ${curr_config}; do
@@ -325,34 +334,37 @@ parse_config() {
 
 	if [ -n "${unexp_entries}" ]
 	then
-		reg_failure "Error: unexpected keys in config: '${unexp_keys% }'."
+		echo
+		reg_failure "Unexpected keys in config: '${unexp_keys% }'."
 		print_msg "Corresponding config entries:"
-		print_msg "${unexp_entries}"
+		print_msg "${unexp_entries%$'\n'}"
 		bad_config=1
 	fi
 
 	if [ -n "${missing_keys% }" ]
 	then
-		reg_failure "Error: missing keys in config: '${missing_keys% }'."
+		echo
+		reg_failure "Missing keys in config: '${missing_keys% }'."
 		print_msg "Corresponding default config entries:"
 		print_msg "${missing_entries}"
 		bad_config=1
 	fi
 
-	if [ -n "${conv_entries}" ]
+	if [ -n "${legacy_entries}" ]
 	then
-		reg_failure "Detected config entries in legacy format: '${conv_keys% }'."
+		echo
+		reg_failure "Config entries for keys '${legacy_keys% }' are in legacy format (missing double-quotes)."
 		print_msg "The following config entries must be converted to the new config format:"
-		print_msg "${conv_entries}"
-		must_convert=1
+		print_msg "${legacy_entries%$'\n'}"
+		bad_config=1
 	fi
 
-	[ -n "${bad_config}" ] || [ -n "${must_convert}" ] && return 2
+	[ -n "${bad_config}" ] && return 2
 	:
 }
 
 load_config() {
-	local missing_keys='' missing_entries='' unexp_keys='' unexp_entries='' conv_keys='' conv_entries='' fixed_config='' key val line fix cnt val_res \
+	local missing_keys='' missing_entries='' unexp_keys='' unexp_entries='' legacy_keys='' legacy_entries='' fixed_config='' key val line fix cnt val_res \
 		rm_unexp add_missing conv_legacy temp_config_f="${tmp_abl_dir}/fix-config.tmp" \
 		tip_msg="Fix your config file '${config_file}' or generate default config using 'service adblock-lean gen_config'."
 
@@ -367,12 +379,12 @@ load_config() {
 
 	[ "${msgs_dest}" != "/dev/tty" ] && { log_msg "${tip_msg}"; return 1; }
 
-	[ -z "$unexp_keys" ] && [ -z "$missing_keys" ] && [ -z "$conv_entries" ] &&
+	[ -z "$unexp_keys" ] && [ -z "$missing_keys" ] && [ -z "$legacy_entries" ] &&
 		{ reg_failure "Internal error when parsing config."; return 1; }
 
 	[ -n "$unexp_keys" ] && rm_unexp="Remove unexpected entries from the config"
 	[ -n "$missing_keys" ] && add_missing="Re-add missing config entries with default values"
-	[ -n "$conv_entries" ] && conv_legacy="Convert legacy config entries to the new format"
+	[ -n "$legacy_entries" ] && conv_legacy="Convert legacy config entries to the new format"
 
 	echo
 	print_msg "${blue}Perform following automatic changes?${n_c}"
@@ -407,7 +419,7 @@ load_config() {
 	)"
 
 	printf '%s\n' "${fixed_config}" > "${temp_config_f}" || return 1
-	unset missing_keys missing_entries unexp_keys unexp_entries conv_keys conv_entries
+	unset missing_keys missing_entries unexp_keys unexp_entries legacy_keys legacy_entries
 	parse_config "${temp_config_f}"
 	val_res=${?}
 	rm -f "${temp_config_f}"
@@ -426,8 +438,9 @@ write_config()
 	[ -z "${1}" ] && { reg_failure "write_config(): no config passed."; return 1; }
 
 	mkdir -p "${tmp_abl_dir}"
-	printf '%s\n' "${1}" > "${tmp_config}" || { reg_failure "Error: failed to write to file '${tmp_config}'."; return 1; }
+	printf '%s\n' "${1}" > "${tmp_config}" || { reg_failure "Failed to write to file '${tmp_config}'."; return 1; }
 
+	echo
 	log_msg "Saving new config file to '${config_file}'."
 	try_mv "${tmp_config}" "${config_file}" && return 0
 	rm -f "${tmp_config}"
@@ -489,7 +502,7 @@ try_export_existing_blocklist()
 {
 	export_existing_blocklist
 	case ${?} in
-		1) reg_failure "Error: failed to export the blocklist."; return 1 ;;
+		1) reg_failure "Failed to export the blocklist."; return 1 ;;
 		2) return 2
 	esac
 	:	
@@ -552,16 +565,16 @@ download_and_process_list_part()
 	local dest_file="${abl_dir}/${list_type}.${list_id}" compress='' convert_to_local='' \
 		min_list_part_line_count='' list_part_size_B='' list_part_size_KB=''
 
-	[ -z "${list_id}" ] && { reg_failure "${me}: Error: no list id specified."; return 1; }
+	[ -z "${list_id}" ] && { reg_failure "${me}: No list id specified."; return 1; }
 	case ${list_type} in
 		allowlist) ;;
 		blocklist)
 			convert_to_local="; s/^\(address=\|server=\)/local=/"
 			dest_file="${dest_file}.gz"
 			compress=1 ;;
-		*) reg_failure "${me}: Error: missing or invalid list type '${list_type}'"; return 1
+		*) reg_failure "${me}: Missing or invalid list type '${list_type}'"; return 1
 	esac
-	[ -z "${list_url}" ] && { reg_failure "${me}: Error: no URL specified."; return 1; }
+	[ -z "${list_url}" ] && { reg_failure "${me}: no URL specified."; return 1; }
 
 	eval "min_list_part_line_count=\"\${min_${list_type}_part_line_count}\""
 
@@ -685,7 +698,7 @@ gen_list_parts()
 
 			fix_line_cnt list_part_line_count
 			case ${list_part_line_count} in
-				''|*[!0-9]*) reg_failure "Error: failed to process local ${list_type}."; return 1 ;;
+				''|*[!0-9]*) reg_failure "Failed to process local ${list_type}."; return 1 ;;
 				0) log_msg -warn "No lines remaining in local ${list_type} after sanitization." ;;
 				*)
 					log_msg "Sanitized local ${list_type} line count: $(int2human ${list_part_line_count})."
@@ -693,7 +706,7 @@ gen_list_parts()
 			esac
 		elif [ -f "${local_list_path}" ]
 		then
-			log_msg -warn "Warning: local ${list_type} file is empty."
+			log_msg -warn "Local ${list_type} file is empty."
 		else
 			log_msg -blue "No local ${list_type} identified."
 		fi
@@ -722,7 +735,7 @@ gen_list_parts()
 						if [ "${list_type}" = allowlist ]
 						then
 							cat "${abl_dir}/${list_type}.${list_id}" >> "${abl_dir}/allowlist" ||
-								{ reg_failure "Error: Failed to merge allowlist part."; return 1; }
+								{ reg_failure "Failed to merge allowlist part."; return 1; }
 						fi
 						continue 2 ;;
 					1) return 1 ;;
@@ -855,7 +868,7 @@ restart_dnsmasq()
 	reg_action -blue "Restarting dnsmasq." || return 1
 
 	/etc/init.d/dnsmasq restart &> /dev/null || 
-		{ reg_failure "Error: failed to restart dnsmasq."; return 1; }
+		{ reg_failure "Failed to restart dnsmasq."; return 1; }
 	
 	reg_action "Waiting for dnsmasq initialization." || return 1
 	local dnsmasq_ok=
@@ -865,7 +878,7 @@ restart_dnsmasq()
 		sleep 1;
 	done
 
-	[ -z "$dnsmasq_ok" ] && { reg_failure "Error: dnsmasq initialization failed. Failed to restart dnsmasq."; return 1; }
+	[ -z "$dnsmasq_ok" ] && { reg_failure "dnsmasq initialization failed."; return 1; }
 
 	log_msg -green "Restart of dnsmasq completed."
 	:
@@ -887,7 +900,7 @@ export_existing_blocklist()
 	then
 		reg_action -blue "Exporting and saving existing uncompressed blocklist." || return 1
 		gzip -f /tmp/dnsmasq.d/blocklist ||
-			{ reg_failure "Error: failed to compress '/tmp/dnsmasq.d/blocklist'."; return 1; }
+			{ reg_failure "Failed to compress '/tmp/dnsmasq.d/blocklist'."; return 1; }
 		try_mv /tmp/dnsmasq.d/blocklist.gz "${abl_dir}/prev_blocklist.gz" || return 1
 		return 0
 	else
@@ -905,11 +918,11 @@ restore_saved_blocklist()
 		if [ "${compress_blocklist}" != 1 ]
 		then
 			gunzip -f "${abl_dir}/blocklist.gz" ||
-				{ reg_failure "Error: failed to extract '${abl_dir}/blocklist.gz'."; return 1; }
+				{ reg_failure "Failed to extract '${abl_dir}/blocklist.gz'."; return 1; }
 
 		fi
 		import_blocklist_file ||
-			{ reg_failure "Error: failed to import the blocklist file."; return 1; }
+			{ reg_failure "Failed to import the blocklist file."; return 1; }
 		return 0
 	else
 		reg_failure "No previous blocklist file found."
@@ -930,7 +943,7 @@ import_blocklist_file()
 	then
 		printf "conf-script=\"busybox sh /tmp/dnsmasq.d/.extract_blocklist\"\n" > /tmp/dnsmasq.d/conf-script &&
 		printf "busybox gunzip -c /tmp/dnsmasq.d/.blocklist.gz\nexit 0\n" > /tmp/dnsmasq.d/.extract_blocklist ||
-			{ reg_failure "Error: failed to create conf-script for dnsmasq."; return 1; }
+			{ reg_failure "Failed to create conf-script for dnsmasq."; return 1; }
 	fi
 
 	:
@@ -980,8 +993,8 @@ update_pid_action() {
 	case ${?} in
 		3) ;;
 		1) return 1 ;;
-		2) reg_failure "update_pid_action(): Error: pid file '${pid_file}' has unexpected pid '${_pid}'."; return 1 ;;
-		0) reg_failure "update_pid_action(): Error: pid file '${pid_file}' not found."; return 1
+		2) reg_failure "update_pid_action(): pid file '${pid_file}' has unexpected pid '${_pid}'."; return 1 ;;
+		0) reg_failure "update_pid_action(): pid file '${pid_file}' not found."; return 1
 	esac
 	mk_lock -f "${1}"
 	return ${?}
@@ -1011,16 +1024,16 @@ mk_lock()
 		shift
 	fi
 
-	[ -z "${1%.}" ] && { log_msg "mk_lock(): Error: pid action is unspecified."; return 1; }
+	[ -z "${1%.}" ] && { log_msg "mk_lock(): pid action is unspecified."; return 1; }
 	if [ -n "${pid_file}" ]
 	then
 		if [ ! -d "${tmp_abl_dir}" ]
 		then
-			mkdir -p "${tmp_abl_dir}" || { reg_failure "Error: Failed to create directory '${tmp_abl_dir}'."; return 1; }
+			mkdir -p "${tmp_abl_dir}" || { reg_failure "Failed to create directory '${tmp_abl_dir}'."; return 1; }
 		fi
-		printf '%s\n' "${$} ${1%.}" > "${pid_file}" || { reg_failure "Error: Failed to write to pid file '${pid_file}'."; return 1; }
+		printf '%s\n' "${$} ${1%.}" > "${pid_file}" || { reg_failure "Failed to write to pid file '${pid_file}'."; return 1; }
 	else
-		reg_failure "Internal error: \${pid_file} variable is unset."
+		reg_failure "\${pid_file} variable is unset."
 		return 1
 	fi
 	:
@@ -1030,7 +1043,7 @@ rm_lock()
 {
 	if [ -f "${pid_file}" ]
 	then
-		rm -f "${pid_file}" || { reg_failure "Error: Failed to delete the pid file '${pid_file}'."; return 1; }
+		rm -f "${pid_file}" || { reg_failure "Failed to delete the pid file '${pid_file}'."; return 1; }
 	fi
 	:
 }
@@ -1043,21 +1056,21 @@ rm_lock()
 check_lock()
 {
 	unset _pid pid_action
-	[ -z "${pid_file}" ] && { reg_failure "Internal error: \${pid_file} variable is unset."; return 1; }
+	[ -z "${pid_file}" ] && { reg_failure "\${pid_file} variable is unset."; return 1; }
 	[ ! -f "${pid_file}" ] && return 0
 	if read -r _pid pid_action < "${pid_file}"
 	then
 		case "${_pid}" in
 			${$}) return 3 ;;
-			*[!0-9]*) reg_failure "Error: pid file '${pid_file}' contains unexpected string."; return 1 ;;
+			*[!0-9]*) reg_failure "pid file '${pid_file}' contains unexpected string."; return 1 ;;
 			*) kill -0 "${_pid}" 2>/dev/null && return 2
 		esac
 	else
-		reg_failure "Error: Failed to read the pid file '${pid_file}'."
+		reg_failure "Failed to read the pid file '${pid_file}'."
 		return 1
 	fi
 
-	log_msg -warn "Warning: detected stale pid file '${pid_file}'. Removing."
+	log_msg -warn "Detected stale pid file '${pid_file}'. Removing."
 	rm_lock || return 1
 	:
 }
@@ -1096,10 +1109,10 @@ reg_action()
 		esac
 	done
 
-	[ -z "${nolog}" ] && log_msg "${color}" "${msg}"
+	[ -z "${nolog}" ] && log_msg "${color}" "${msg% }"
 	if [ -n "${lock_req}" ]
 	then
-		update_pid_action "${msg}" || return 1
+		update_pid_action "${msg% }" || return 1
 	fi
 	:
 }
@@ -1138,7 +1151,7 @@ init_command()
 			reg_action -purple "Restarting adblock-lean." || exit 1
 			cleanup_req=1 kill_req=1 lock_req=1 ;;
 		*)
-			reg_failure "Error: invalid action '${action}'."
+			reg_failure "Invalid action '${action}'."
 			exit 1
 	esac
 
@@ -1149,7 +1162,7 @@ init_command()
 		case ${?} in
 			1) exit 1 ;;
 			2)
-				reg_failure "Error: failed to kill running adblock-lean processes."
+				reg_failure "Failed to kill running adblock-lean processes."
 				exit 1
 		esac
 	fi
@@ -1191,7 +1204,7 @@ gen_stats()
 gen_config()
 {
 	init_command gen_config || exit 1
-	local missing_keys='' missing_entries='' unexp_keys='' unexp_entries='' conv_keys='' conv_entries=''
+	local missing_keys='' missing_entries='' unexp_keys='' unexp_entries='' legacy_keys='' legacy_entries=''
 	reg_action -purple "Generating new default config for adblock-lean." || exit 1
 	if [ "${msgs_dest}" = "/dev/tty" ] && [ -f "${config_file}" ]
 	then
@@ -1209,7 +1222,7 @@ gen_config()
 boot()
 {
 	init_command boot || exit 1
-	reg_action -purple "Sleeping for: ${boot_start_delay_s} seconds." || exit 1
+	reg_action -purple "Sleeping for ${boot_start_delay_s} seconds." || exit 1
 	sleep "${boot_start_delay_s}"
 	start "$@"
 }
@@ -1300,7 +1313,7 @@ start()
 
 		if ! restore_saved_blocklist
 		then
-			reg_failure "Error: failed to restore saved blocklist."
+			reg_failure "Failed to restore saved blocklist."
 			stop 1
 		fi
 
@@ -1441,7 +1454,7 @@ resume()
 
 	reg_action -purple "Resuming adblock-lean." || exit 1
 	restore_saved_blocklist || 
-		{ reg_failure "Error: failed to restore saved blocklist. Stopping adblock-lean."; stop 1; }
+		{ reg_failure "Failed to restore saved blocklist. Stopping adblock-lean."; stop 1; }
 	restart_dnsmasq || exit 1
 	log_msg -purple "adblock-lean is now resumed."
 	exit 0
